#!/bin/bash
set -e
source "/etc/companionpi/settings.env"

OUTPUT_FILE="/etc/dnsmasq.d/companionpi.conf"
echo "# Auto-generated by generate-dnsmasq.sh" | sudo tee "$OUTPUT_FILE" > /dev/null

log() {
  echo "[dnsmasq-gen] $1"
}

add_dhcp_range() {
  IFACE=$1
  PREFIX=${IFACE^^}
  DHCP_ENABLED_VAR="${PREFIX}_DHCP_SERVER_ENABLED"
  START_VAR="${PREFIX}_DHCP_RANGE_START"
  END_VAR="${PREFIX}_DHCP_RANGE_END"
  LEASE_VAR="${PREFIX}_DHCP_LEASE_TIME"
  ROUTER_VAR="${PREFIX}_DHCP_ROUTER"
  DNS_VAR="${PREFIX}_DHCP_DNS"
  NETMASK_VAR="${PREFIX}_DHCP_NETMASK"

  if [[ "${!DHCP_ENABLED_VAR}" == "true" ]]; then
    RANGE_START=${!START_VAR}
    RANGE_END=${!END_VAR}
    LEASE=${!LEASE_VAR:-12h}
    NETMASK=${!NETMASK_VAR:-255.255.255.0}

    log "Adding DHCP config for $IFACE ($RANGE_START - $RANGE_END, $LEASE)"

    echo "interface=$IFACE" | sudo tee -a "$OUTPUT_FILE" > /dev/null
    echo "dhcp-range=$RANGE_START,$RANGE_END,$NETMASK,$LEASE" | sudo tee -a "$OUTPUT_FILE" > /dev/null

    if [[ -n "${!ROUTER_VAR}" ]]; then
      echo "dhcp-option=3,${!ROUTER_VAR}" | sudo tee -a "$OUTPUT_FILE" > /dev/null
    fi

    if [[ -n "${!DNS_VAR}" ]]; then
      echo "dhcp-option=6,${!DNS_VAR}" | sudo tee -a "$OUTPUT_FILE" > /dev/null
    fi
  fi
}

log "Generating dnsmasq configuration..."

eth_ifaces=$(grep -oP '^ETH\d+_DHCP_SERVER_ENABLED' "$SCRIPT_DIR/settings.env" | cut -d_ -f1 | tr '[:upper:]' '[:lower:]' | sort -u)
wlan_ifaces=$(grep -oP '^WLAN\d+_DHCP_SERVER_ENABLED' "$SCRIPT_DIR/settings.env" | cut -d_ -f1 | tr '[:upper:]' '[:lower:]' | sort -u)

for iface in $eth_ifaces; do
  add_dhcp_range "$iface"
done

for iface in $wlan_ifaces; do
  add_dhcp_range "$iface"
done

log "Restarting dnsmasq..."
sudo systemctl restart dnsmasq

log "Done."
