#!/bin/bash
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/settings.env"

OUTPUT_FILE="/etc/dnsmasq.d/companionpi.conf"
echo "# Auto-generated by netconfig.sh" | sudo tee "$OUTPUT_FILE" > /dev/null

log() {
  echo "[dnsmasq-gen] $1"
}

add_dhcp_range() {
  IFACE=$1
  PREFIX=${IFACE^^}
  DHCP_ENABLED_VAR="${PREFIX}_DHCP_SERVER_ENABLED"
  START_VAR="${PREFIX}_DHCP_RANGE_START"
  END_VAR="${PREFIX}_DHCP_RANGE_END}"

  if [[ "${!DHCP_ENABLED_VAR}" == "true" ]]; then
    RANGE_START=${!START_VAR}
    RANGE_END=${!END_VAR}
    log "Adding DHCP range for $IFACE: $RANGE_START - $RANGE_END"
    echo "interface=$IFACE" | sudo tee -a "$OUTPUT_FILE" > /dev/null
    echo "dhcp-range=$RANGE_START,$RANGE_END,12h" | sudo tee -a "$OUTPUT_FILE" > /dev/null
  fi
}

log "Generating dnsmasq configuration..."

# ETH interfaces
eth_ifaces=$(grep -oP '^ETH\d+_ENABLED' "$SCRIPT_DIR/settings.env" | cut -d_ -f1 | sort -u)
for IFACE in $eth_ifaces; do
  add_dhcp_range "$IFACE"
done

# WLAN interfaces
wlan_ifaces=$(grep -oP '^WLAN\d+_MODE' "$SCRIPT_DIR/settings.env" | cut -d_ -f1 | sort -u)
for IFACE in $wlan_ifaces; do
  add_dhcp_range "$IFACE"
done

log "Restarting dnsmasq..."
sudo systemctl restart dnsmasq

log "Done."
